popup component
sonac/neon-pics pull request #3
Opened 2017-12-21 10:46 UTC by sonac

2017-12-21 10:58 UTC, citizen4371 commented on app/assets/javascripts/src/PicCompare.jsx
> +      .then(data => this.setState({ picUrls: data }));
.then(picUrls => this.setState(state => ({...state, picUrls})))

2017-12-21 11:00 UTC, citizen4371 commented on app/assets/javascripts/src/PicCompare.jsx
> +    this.setState({curPics: newPair})
this.setState(state => ({...state, curPics: state.curPics.map(x => x + 2)}))

2017-12-21 11:00 UTC, citizen4371 commented on app/assets/javascripts/src/PicCompare.jsx
> +    this.setState({curPics: newPair})
вместо всего тела функции

2017-12-21 11:03 UTC, citizen4371 requested changes

2017-12-21 11:03 UTC, citizen4371 commented on app/assets/javascripts/src/PicCompare.jsx
> +  render() {
const { picUrls, curPics } = this.state;

2017-12-21 11:03 UTC, citizen4371 commented on app/assets/javascripts/src/PicCompare.jsx
> +        <img src={this.state.picUrlsp[curPics[0]]} alt="First pic"> <img src={this.state.picUrlsp[curPics[1]]} alt="Second pic">
this.state.picUrlsp[curPics[0]] поменяй на picUrls[curPics[0]]

2017-12-27 14:17 UTC, eillasti commented
outdated?

2017-12-27 14:48 UTC, sonac commented
yep

2017-12-28 08:26 UTC, closed without merging